// <auto-generated />
namespace Projeto_Academico.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addclienteprojeto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addclienteprojeto));
        
        string IMigrationMetadata.Id
        {
            get { return "201710261814579_add-cliente-projeto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
