// <auto-generated />
namespace Projeto_Academico.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class criacaodb070517 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criacaodb070517));
        
        string IMigrationMetadata.Id
        {
            get { return "201705080525538_criacao-db-07-05-17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
