// <auto-generated />
namespace Projeto_Academico.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20062017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20062017));
        
        string IMigrationMetadata.Id
        {
            get { return "201706200341301_20-06-2017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
